import { ArrowRight, BookOpenCheck, CalendarCheck, Clock3, ExternalLink, FileText, Info, ShieldCheck } from 'lucide-react';
import PageHeader from '../../components/ui/PageHeader';
import styles from './Services.module.css';

const DATA = {
  matricula: ['Matrícula', 'Itinerário Formativo', 'Escolha componentes que complementam sua formação acadêmica.', 'Escolhas abertas até 28 de agosto.', [['Etapa', 'Escolha de trilha'], ['Disponíveis', '8 créditos'], ['Prazo', '6 dias']], [['Tecnologia e Sociedade', 'Trilha interdisciplinar', 'Quarta · 17:30'], ['Empreendedorismo e Inovação', 'Trilha de negócios', 'Sábado · 09:00'], ['Cidadania e Sustentabilidade', 'Trilha humanística', 'On-line']], 'Selecionar'],
  rematricula: ['Secretaria', 'Rematrícula', 'Acompanhe as etapas para confirmar seu próximo semestre.', 'Revise seus dados antes da confirmação final.', [['Período', '2026/2'], ['Situação', 'Em análise'], ['Previsão', '24/08']], [['Dados cadastrais', 'Conferidos em 20/08', 'Concluído'], ['Contrato educacional', 'Aceite digital registrado', 'Concluído'], ['Grade sugerida', '6 disciplinas disponíveis', 'Revisar agora']], 'Revisar'],
  'matricula-online': ['Matrícula', 'Matrícula on-line', 'Monte sua grade respeitando pré-requisitos e vagas.', 'Você pode selecionar até 28 créditos.', [['Selecionadas', '5 disciplinas'], ['Carga horária', '342 horas'], ['Créditos', '18 de 28']], [['Desenvolvimento Web II', 'Turma 02 · 12 vagas', 'Segunda e quarta'], ['Banco de Dados II', 'Turma 01 · 8 vagas', 'Terça-feira'], ['Engenharia de Software II', 'Turma 03 · 16 vagas', 'Quinta-feira']], 'Ver turmas'],
  competencias: ['Central do Aluno', 'Competências e habilidades', 'Acompanhe as competências previstas para sua formação.', 'Perfil atualizado com os resultados do último bimestre.', [['Desenvolvidas', '12'], ['Em evolução', '5'], ['Evidências', '28']], [['Pensamento computacional', 'Nível avançado', '8 evidências'], ['Comunicação e colaboração', 'Nível intermediário', '6 evidências'], ['Resolução de problemas', 'Nível avançado', '7 evidências']], 'Ver evidências'],
  desempenho: ['Central do Aluno', 'Desempenho acadêmico', 'Uma visão consolidada da sua evolução no semestre.', 'Indicadores atualizados em 21/08/2026.', [['Média geral', '8,4'], ['Frequência', '96%'], ['Créditos', '18']], [['Desenvolvimento Web I', 'Média 9,1', 'Acima da média'], ['Algoritmos e Programação I', 'Média 8,6', 'Bom desempenho'], ['Ética e Cidadania', 'Média 7,8', 'Desempenho estável']], 'Abrir'],
  'nota-falta': ['Central do Aluno', 'Nota e falta unificada', 'Consulte notas e frequência em um único lugar.', 'Dados sujeitos ao fechamento do diário.', [['Disciplinas', '6'], ['Média parcial', '8,4'], ['Faltas', '4']], [['Algoritmos e Programação I', 'Média 8,7 · 0 faltas', 'Em andamento'], ['Fundamentos de Sistemas', 'Média 8,2 · 2 faltas', 'Em andamento'], ['Organização de Computadores', 'Média 7,9 · 2 faltas', 'Em andamento']], 'Detalhes'],
  ocorrencias: ['Central do Aluno', 'Ocorrências acadêmicas', 'Acompanhe registros relacionados à sua vida acadêmica.', 'Nenhuma ocorrência exige ação imediata.', [['Em aberto', '1'], ['Resolvidas', '4'], ['Atualização', '18/08']], [['Documento pendente', 'Comprovante de residência', 'Prazo: 30/08'], ['Ajuste de frequência', 'Ética e Cidadania', 'Resolvido'], ['Validação cadastral', 'Dados pessoais', 'Resolvido']], 'Consultar'],
  'plano-aula': ['Central do Aluno', 'Planos de aula', 'Consulte objetivos e conteúdos das disciplinas.', 'Planos atualizados pelos professores.', [['Disciplinas', '6'], ['Publicados', '6'], ['Atualizados', '4']], [['Desenvolvimento Web I', 'Componentização e estado', 'Atualizado hoje'], ['Algoritmos e Programação I', 'Estruturas condicionais', 'Atualizado ontem'], ['Organização de Computadores', 'Memória e processadores', '19/08']], 'Abrir plano'],
  negociacao: ['Financeiro', 'Negociação on-line', 'Consulte opções para regularização financeira.', 'Simulações fictícias, sem compromisso financeiro.', [['Saldo', 'R$ 890,50'], ['Opções', '3'], ['Validade', '31/08']], [['Pagamento à vista', 'Desconto demonstrativo de 5%', 'R$ 845,98'], ['Parcelamento em 3 vezes', 'Sem entrada', '3 × R$ 296,83'], ['Parcelamento em 6 vezes', 'Primeira em setembro', '6 × R$ 153,40']], 'Simular'],
  avaliacao: ['Comunidade', 'Avaliação institucional', 'Sua percepção ajuda a aprimorar a universidade.', 'Disponível até 15 de setembro.', [['Progresso', '40%'], ['Respondidas', '2 de 5'], ['Tempo', '6 minutos']], [['Experiência acadêmica', '8 perguntas', 'Concluída'], ['Infraestrutura do campus', '6 perguntas', 'Em andamento'], ['Atendimento e serviços', '5 perguntas', 'Não iniciada']], 'Responder'],
  canvas: ['Ambiente virtual', 'Canvas', 'Acesse materiais e atividades das disciplinas.', 'O protótipo não acessa o serviço externo oficial.', [['Disciplinas', '6'], ['Atividades', '4'], ['Avisos', '3']], [['Desenvolvimento Web I', 'Projeto responsivo', 'Entrega em 27/08'], ['Algoritmos e Programação I', 'Lista 03', 'Entrega em 29/08'], ['Ética e Cidadania', 'Fórum temático', 'Entrega em 02/09']], 'Abrir ambiente', true],
  proato: ['Apoio ao estudante', 'PROATO Inclusão', 'Conheça recursos de acessibilidade e permanência.', 'Atendimento confidencial mediante agendamento.', [['Atendimento', '02/09'], ['Solicitações', '1'], ['Canal', 'Híbrido']], [['Acompanhamento pedagógico', 'Orientação individualizada', 'Horários disponíveis'], ['Recursos de acessibilidade', 'Tecnologias e adaptações', 'Solicitar análise'], ['Orientação à comunidade', 'Apoio a alunos e docentes', 'Ver materiais']], 'Conhecer', true],
};

export default function Services({ type }) {
  const [eyebrow, title, description, notice, stats, items, action, external] = DATA[type];
  return <div className={styles.page}>
    <PageHeader eyebrow={eyebrow} title={title} description={description} />
    <div className={styles.notice}><Info size={18} />{notice}</div>
    <section className={styles.summary}>{stats.map(([label, value]) => <div className={styles.stat} key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Visão geral</h2><p>Informações e ações disponíveis para você.</p></div><ShieldCheck size={22} /></div>
      {items.map(([itemTitle, detail, meta], index) => <article className={styles.item} key={itemTitle}><div className={styles.itemIcon}>{index === 0 ? <BookOpenCheck /> : index === 1 ? <CalendarCheck /> : <FileText />}</div><div className={styles.itemCopy}><h3>{itemTitle}</h3><p>{detail}</p><span><Clock3 size={13} />{meta}</span></div><button>{action}{external ? <ExternalLink size={15} /> : <ArrowRight size={15} />}</button></article>)}
    </section>
    <p className={styles.disclaimer}>Conteúdo fictício criado para demonstração desta proposta de redesign.</p>
  </div>;
}
